import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/Navbar';
import { BookmarksProvider } from './context/bookmarksContext';
import { SideBar } from '@/components/SideBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BookmarksProvider>
          <div className='flex flex-1'>
            <SideBar />
            <div className='flex flex-col flex-1'>
              <Navbar />
              {children}
            </div>
          </div>
        </BookmarksProvider>
      </body>
    </html>
  );
}
